name: Build LaTeX document

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set GITHUB_RUN_URL environment variable
        run: echo "GITHUB_RUN_URL=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV

      - name: Compile LaTeX document
        id: latex_build
        uses: xu-cheng/latex-action@v3
        with:
          root_file: template.tex
          #extra_fonts: |
           # ./fonts/*.otf
          args: -pdf -file-line-error -interaction=nonstopmode -jobname="./DANIEL_GULDBERG_AAES_CV" template.tex     
          #continue-on-error: true # Continue even if there's an error

      # Rename the output file to Daniel_Guldberg_Aaes_CV.pdf
      - name: Rename output PDF
        if: success()
        run: mv -f template.pdf Daniel_Guldberg_Aaes_CV.pdf

      # Upload the PDF only if it was successfully created
      - name: Upload PDF file
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          name: nightly
          tag_name: nightly
          files: DANIEL_GULDBERG_AAES_CV.pdf
          fail_on_unmatched_files: true
