name: Build LaTeX document

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set GITHUB_RUN_URL environment variable
        run: echo "GITHUB_RUN_URL=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV

      - name: Compile LaTeX document
        id: latex_build
        uses: xu-cheng/latex-action@v3
        with:
          root_file: template.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -jobname=DANIEL_GULDBERG_AAES_CV

      # Upload the PDF only if it was successfully created
      - name: Upload PDF file
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          name: CV
          tag_name: latest
          files: DANIEL_GULDBERG_AAES_CV.pdf
          fail_on_unmatched_files: true
